apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: "{{ .Values.qbittorrent.image.repository }}:{{ .Values.qbittorrent.image.tag }}"
          env:
            - name: PUID
              value: "{{ .Values.puid }}"
            - name: PGID
              value: "{{ .Values.pgid }}"
            - name: TZ
              value: {{ .Values.timezone }}
            - name: WEBUI_PORT
              value: "{{ .Values.qbittorrent.webuiPort }}"
            - name: TORRENTING_PORT
              value: "{{ .Values.qbittorrent.torrentPort }}"
          ports:
            - containerPort: {{ .Values.qbittorrent.webuiPort }}
            - containerPort: {{ .Values.qbittorrent.torrentPort }}
              protocol: TCP
            - containerPort: {{ .Values.qbittorrent.torrentPort }}
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /config
              subPath: qbittorrent-config
            - name: data
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dl-data
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    expose: lan
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: {{ .Values.qbittorrent.webuiPort }}
      targetPort: {{ .Values.qbittorrent.webuiPort }}
      protocol: TCP
    - name: torrent-tcp
      port: {{ .Values.qbittorrent.torrentPort }}
      targetPort: {{ .Values.qbittorrent.torrentPort }}
      protocol: TCP
    - name: torrent-udp
      port: {{ .Values.qbittorrent.torrentPort }}
      targetPort: {{ .Values.qbittorrent.torrentPort }}
      protocol: UDP
