apiVersion: v1
kind: PersistentVolume
metadata:
  name: dl-data-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClassName }}
  local:
    path: {{ .Values.storage.hostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.storage.nodeName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dl-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  volumeName: dl-data-pv
  resources:
    requests:
      storage: {{ .Values.storage.size }}
